### ISSUE TITLE
No content element within NewContentElementWizard in TYPO3 12.3

### ISSUE THREAD

**Issue by xima-wla** [maikschneider/bw_static_template#15]
With the TYPO3 update to 12.3, the content element bw_static_template is no longer displayed in the special tab of the NewContentElementWizard.

**Comment by maikschneider** [comment]
Fixed in #16 (see `feature/v3` branch)
Please test.

**Comment by maikschneider** [comment]
@xima-wla Is this working for you or do you need further adjustments?

**Comment by xima-wla** [comment]
@maikschneider: That works fine in TYPO3 12.3! Thanks.

**Comment by maikschneider** [comment]
Done in [v3.0.0](https://github.com/maikschneider/bw_static_template/releases/tag/v3.0.0)
