### ISSUE TITLE
Content element title

### ISSUE THREAD

**Issue by konradmichalik** [maikschneider/bw_static_template#6]
Hej there,

is it possible to provide an optional title for the TYPO3 content element "Static Template" to have a better overview in the backend web module to distinguish between the different static elements. 

Thanks so far

**Comment by maikschneider** [comment]
Hey,

currently the template path is used as headline. I guess these paths do look too familiar to you? 
Did you know that you can use just a single template name (which should be quite unique)?

The `rowDescription` field, which outputs a comment below the element preview, isn't sufficient either?

**Comment by konradmichalik** [comment]
Thanks for your reply.

We're often using the same template with different kind of provided data which controls the expression of the representation. 

But I will try the hint with the `rowDescription` field, sounds simple enough. Cheers!

**Comment by maikschneider** [comment]
@jackd248 Ah, okay - I didn't thought about a heavy reuse of templates. 

Maybe a configurable backend preview could be useful: I added a new field  in the [feature/backend-preview](https://github.com/maikschneider/bw_static_template/tree/feature/backend-preview) branch. There you can configure preview files just like for the frontend.
