### ISSUE TITLE
JSON file support

### ISSUE THREAD

**Issue by konradmichalik** [maikschneider/bw_static_template#7]
Hej there,

we're using the extension to work on a continuous prototype within a new TYPO3 project. Because we can't merge the database  only one frontend developer can actually work simultaneously on the prototype. 

Is there a way to use "mergable" json files for providing the temporary data or do you have another idea how to solve this kind of issue? 

Thanks

**Comment by maikschneider** [comment]
Hi @jackd248, thanks for your suggestion - sounds like a useful feature!

I just added a new option to load JSON data from file, check out the [feature/json-file](https://github.com/maikschneider/bw_static_template/tree/feature/json-file) branch. 

Is this working for you?

**Comment by konradmichalik** [comment]
I was trying this new feature and I think this helps a lot for our collaborative work while merging different progress status of the prototype.

Thanks for solving this problem so fast!
